(define (problem tokyo_trip_plan)
  (:domain tokyo_trip)

  (:objects
    tokyo_tower senso_ji akihabara meiji_shrine tsukiji_market odaiba shinjuku_garden - location
    day1 day2 day3 day4 day5 - day
    ts_0 ts_1 ts_2 ts_3 ts_4 ts_5 ts_6 ts_7 ts_8 ts_9 ts_10 ts_11 ts_12 ts_13 ts_14 ts_15 ts_16 ts_17 ts_18 ts_19 ts_20 ts_21 ts_22 ts_23 - time_slot
  )

  (:init
    (at tokyo_tower)
    (available tokyo_tower)
    (available senso_ji)
    (available akihabara)
    (available meiji_shrine)
    (available tsukiji_market)
    (available odaiba)
    (available shinjuku_garden)
    (day_now day1)
    (time_slot_now ts_8)
    (next_day day1 day2)
    (next_day day2 day3)
    (next_day day3 day4)
    (next_day day4 day5)
    (next_slot ts_0 ts_1)
    (next_slot ts_1 ts_2)
    (next_slot ts_2 ts_3)
    (next_slot ts_3 ts_4)
    (next_slot ts_4 ts_5)
    (next_slot ts_5 ts_6)
    (next_slot ts_6 ts_7)
    (next_slot ts_7 ts_8)
    (next_slot ts_8 ts_9)
    (next_slot ts_9 ts_10)
    (next_slot ts_10 ts_11)
    (next_slot ts_11 ts_12)
    (next_slot ts_12 ts_13)
    (next_slot ts_13 ts_14)
    (next_slot ts_14 ts_15)
    (next_slot ts_15 ts_16)
    (next_slot ts_16 ts_17)
    (next_slot ts_17 ts_18)
    (next_slot ts_18 ts_19)
    (next_slot ts_19 ts_20)
    (next_slot ts_20 ts_21)
    (next_slot ts_21 ts_22)
    (next_slot ts_22 ts_23)
    (= (total-cost) 0)

    (= (play_time tokyo_tower) 121)
    (= (play_time senso_ji) 121)
    (= (play_time akihabara) 121)
    (= (play_time meiji_shrine) 121)
    (= (play_time tsukiji_market) 121)
    (= (play_time odaiba) 121)
    (= (play_time shinjuku_garden) 121)
    (= (travel_time tokyo_tower senso_ji) 62)
    (= (travel_time tokyo_tower akihabara) 123)
    (= (travel_time tokyo_tower meiji_shrine) 185)
    (= (travel_time tokyo_tower tsukiji_market) 240)
    (= (travel_time tokyo_tower odaiba) 300)
    (= (travel_time tokyo_tower shinjuku_garden) 123)
    (= (travel_time senso_ji tokyo_tower) 62)
    (= (travel_time senso_ji akihabara) 62)
    (= (travel_time senso_ji meiji_shrine) 123)
    (= (travel_time senso_ji tsukiji_market) 185)
    (= (travel_time senso_ji odaiba) 240)
    (= (travel_time senso_ji shinjuku_garden) 185)
    (= (travel_time akihabara tokyo_tower) 123)
    (= (travel_time akihabara senso_ji) 62)
    (= (travel_time akihabara meiji_shrine) 123)
    (= (travel_time akihabara tsukiji_market) 185)
    (= (travel_time akihabara odaiba) 240)
    (= (travel_time akihabara shinjuku_garden) 185)
    (= (travel_time meiji_shrine tokyo_tower) 185)
    (= (travel_time meiji_shrine senso_ji) 123)
    (= (travel_time meiji_shrine akihabara) 123)
    (= (travel_time meiji_shrine tsukiji_market) 123)
    (= (travel_time meiji_shrine odaiba) 185)
    (= (travel_time meiji_shrine shinjuku_garden) 62)
    (= (travel_time tsukiji_market tokyo_tower) 240)
    (= (travel_time tsukiji_market senso_ji) 185)
    (= (travel_time tsukiji_market akihabara) 185)
    (= (travel_time tsukiji_market meiji_shrine) 123)
    (= (travel_time tsukiji_market odaiba) 185)
    (= (travel_time tsukiji_market shinjuku_garden) 123)
    (= (travel_time odaiba tokyo_tower) 300)
    (= (travel_time odaiba senso_ji) 240)
    (= (travel_time odaiba akihabara) 240)
    (= (travel_time odaiba meiji_shrine) 185)
    (= (travel_time odaiba tsukiji_market) 185)
    (= (travel_time odaiba shinjuku_garden) 123)
    (= (travel_time shinjuku_garden tokyo_tower) 123)
    (= (travel_time shinjuku_garden senso_ji) 185)
    (= (travel_time shinjuku_garden akihabara) 185)
    (= (travel_time shinjuku_garden meiji_shrine) 62)
    (= (travel_time shinjuku_garden tsukiji_market) 123)
    (= (travel_time shinjuku_garden odaiba) 123)

    (open tokyo_tower day1 ts_8)
    (open tokyo_tower day1 ts_9)
    (open tokyo_tower day1 ts_10)
    (open tokyo_tower day1 ts_11)
    (open tokyo_tower day1 ts_13)
    (open tokyo_tower day1 ts_14)
    (open tokyo_tower day1 ts_15)
    (open tokyo_tower day1 ts_16)
    (open tokyo_tower day1 ts_17)
    (open senso_ji day1 ts_8)
    (open senso_ji day1 ts_9)
    (open senso_ji day1 ts_10)
    (open senso_ji day1 ts_11)
    (open senso_ji day1 ts_12)
    (open senso_ji day1 ts_13)
    (open senso_ji day1 ts_14)
    (open senso_ji day1 ts_15)
    (open senso_ji day1 ts_16)
    (open senso_ji day1 ts_17)
    (open akihabara day1 ts_10)
    (open akihabara day1 ts_11)
    (open akihabara day1 ts_12)
    (open akihabara day1 ts_13)
    (open akihabara day1 ts_14)
    (open akihabara day1 ts_15)
    (open akihabara day1 ts_16)
    (open akihabara day1 ts_17)
    (open akihabara day1 ts_18)
    (open akihabara day1 ts_19)
    (open akihabara day1 ts_20)
    (open akihabara day1 ts_21)
    (open meiji_shrine day1 ts_8)
    (open meiji_shrine day1 ts_9)
    (open meiji_shrine day1 ts_10)
    (open meiji_shrine day1 ts_11)
    (open meiji_shrine day1 ts_12)
    (open meiji_shrine day1 ts_13)
    (open meiji_shrine day1 ts_14)
    (open meiji_shrine day1 ts_15)
    (open tsukiji_market day1 ts_6)
    (open tsukiji_market day1 ts_7)
    (open tsukiji_market day1 ts_8)
    (open tsukiji_market day1 ts_9)
    (open tsukiji_market day1 ts_10)
    (open tsukiji_market day1 ts_11)
    (open tsukiji_market day1 ts_12)
    (open tsukiji_market day1 ts_13)
    (open odaiba day1 ts_10)
    (open odaiba day1 ts_11)
    (open odaiba day1 ts_12)
    (open odaiba day1 ts_13)
    (open odaiba day1 ts_14)
    (open odaiba day1 ts_15)
    (open odaiba day1 ts_16)
    (open odaiba day1 ts_17)
    (open odaiba day1 ts_18)
    (open odaiba day1 ts_19)
    (open odaiba day1 ts_20)
    (open shinjuku_garden day1 ts_9)
    (open shinjuku_garden day1 ts_10)
    (open shinjuku_garden day1 ts_11)
    (open shinjuku_garden day1 ts_12)
    (open shinjuku_garden day1 ts_13)
    (open shinjuku_garden day1 ts_14)
    (open shinjuku_garden day1 ts_15)
    (open shinjuku_garden day1 ts_16)
    (open senso_ji day2 ts_8)
    (open senso_ji day2 ts_9)
    (open senso_ji day2 ts_10)
    (open senso_ji day2 ts_11)
    (open senso_ji day2 ts_12)
    (open senso_ji day2 ts_13)
    (open senso_ji day2 ts_14)
    (open senso_ji day2 ts_15)
    (open senso_ji day2 ts_16)
    (open senso_ji day2 ts_17)
    (open akihabara day2 ts_10)
    (open akihabara day2 ts_11)
    (open akihabara day2 ts_12)
    (open akihabara day2 ts_13)
    (open akihabara day2 ts_14)
    (open akihabara day2 ts_15)
    (open akihabara day2 ts_16)
    (open akihabara day2 ts_17)
    (open akihabara day2 ts_18)
    (open akihabara day2 ts_19)
    (open akihabara day2 ts_20)
    (open akihabara day2 ts_21)
    (open meiji_shrine day2 ts_8)
    (open meiji_shrine day2 ts_9)
    (open meiji_shrine day2 ts_10)
    (open meiji_shrine day2 ts_11)
    (open meiji_shrine day2 ts_12)
    (open meiji_shrine day2 ts_13)
    (open meiji_shrine day2 ts_14)
    (open meiji_shrine day2 ts_15)
    (open tsukiji_market day2 ts_6)
    (open tsukiji_market day2 ts_7)
    (open tsukiji_market day2 ts_8)
    (open tsukiji_market day2 ts_9)
    (open tsukiji_market day2 ts_10)
    (open tsukiji_market day2 ts_11)
    (open tsukiji_market day2 ts_12)
    (open tsukiji_market day2 ts_13)
    (open odaiba day2 ts_10)
    (open odaiba day2 ts_11)
    (open odaiba day2 ts_12)
    (open odaiba day2 ts_13)
    (open odaiba day2 ts_14)
    (open odaiba day2 ts_15)
    (open odaiba day2 ts_16)
    (open odaiba day2 ts_17)
    (open odaiba day2 ts_18)
    (open odaiba day2 ts_19)
    (open odaiba day2 ts_20)
    (open shinjuku_garden day2 ts_9)
    (open shinjuku_garden day2 ts_10)
    (open shinjuku_garden day2 ts_11)
    (open shinjuku_garden day2 ts_12)
    (open shinjuku_garden day2 ts_13)
    (open shinjuku_garden day2 ts_14)
    (open shinjuku_garden day2 ts_15)
    (open shinjuku_garden day2 ts_16)
    (open tokyo_tower day3 ts_9)
    (open tokyo_tower day3 ts_10)
    (open tokyo_tower day3 ts_11)
    (open tokyo_tower day3 ts_12)
    (open tokyo_tower day3 ts_13)
    (open tokyo_tower day3 ts_14)
    (open tokyo_tower day3 ts_15)
    (open tokyo_tower day3 ts_16)
    (open senso_ji day3 ts_8)
    (open senso_ji day3 ts_9)
    (open senso_ji day3 ts_10)
    (open senso_ji day3 ts_11)
    (open senso_ji day3 ts_12)
    (open senso_ji day3 ts_13)
    (open senso_ji day3 ts_14)
    (open senso_ji day3 ts_15)
    (open senso_ji day3 ts_16)
    (open senso_ji day3 ts_17)
    (open akihabara day3 ts_10)
    (open akihabara day3 ts_11)
    (open akihabara day3 ts_12)
    (open akihabara day3 ts_13)
    (open akihabara day3 ts_14)
    (open akihabara day3 ts_15)
    (open akihabara day3 ts_16)
    (open akihabara day3 ts_17)
    (open akihabara day3 ts_18)
    (open akihabara day3 ts_19)
    (open akihabara day3 ts_20)
    (open akihabara day3 ts_21)
    (open meiji_shrine day3 ts_8)
    (open meiji_shrine day3 ts_9)
    (open meiji_shrine day3 ts_10)
    (open meiji_shrine day3 ts_11)
    (open meiji_shrine day3 ts_12)
    (open meiji_shrine day3 ts_13)
    (open meiji_shrine day3 ts_14)
    (open meiji_shrine day3 ts_15)
    (open tsukiji_market day3 ts_6)
    (open tsukiji_market day3 ts_7)
    (open tsukiji_market day3 ts_8)
    (open tsukiji_market day3 ts_9)
    (open tsukiji_market day3 ts_10)
    (open tsukiji_market day3 ts_11)
    (open tsukiji_market day3 ts_12)
    (open tsukiji_market day3 ts_13)
    (open odaiba day3 ts_10)
    (open odaiba day3 ts_11)
    (open odaiba day3 ts_12)
    (open odaiba day3 ts_13)
    (open odaiba day3 ts_14)
    (open odaiba day3 ts_15)
    (open odaiba day3 ts_16)
    (open odaiba day3 ts_17)
    (open odaiba day3 ts_18)
    (open odaiba day3 ts_19)
    (open odaiba day3 ts_20)
    (open shinjuku_garden day3 ts_9)
    (open shinjuku_garden day3 ts_10)
    (open shinjuku_garden day3 ts_11)
    (open shinjuku_garden day3 ts_12)
    (open shinjuku_garden day3 ts_13)
    (open shinjuku_garden day3 ts_14)
    (open shinjuku_garden day3 ts_15)
    (open shinjuku_garden day3 ts_16)
    (open tokyo_tower day4 ts_10)
    (open tokyo_tower day4 ts_11)
    (open tokyo_tower day4 ts_12)
    (open tokyo_tower day4 ts_13)
    (open tokyo_tower day4 ts_14)
    (open tokyo_tower day4 ts_15)
    (open senso_ji day4 ts_8)
    (open senso_ji day4 ts_9)
    (open senso_ji day4 ts_10)
    (open senso_ji day4 ts_11)
    (open senso_ji day4 ts_12)
    (open senso_ji day4 ts_13)
    (open senso_ji day4 ts_14)
    (open senso_ji day4 ts_15)
    (open senso_ji day4 ts_16)
    (open senso_ji day4 ts_17)
    (open akihabara day4 ts_10)
    (open akihabara day4 ts_11)
    (open akihabara day4 ts_12)
    (open akihabara day4 ts_13)
    (open akihabara day4 ts_14)
    (open akihabara day4 ts_15)
    (open akihabara day4 ts_16)
    (open akihabara day4 ts_17)
    (open akihabara day4 ts_18)
    (open akihabara day4 ts_19)
    (open akihabara day4 ts_20)
    (open akihabara day4 ts_21)
    (open meiji_shrine day4 ts_8)
    (open meiji_shrine day4 ts_9)
    (open meiji_shrine day4 ts_10)
    (open meiji_shrine day4 ts_11)
    (open meiji_shrine day4 ts_12)
    (open meiji_shrine day4 ts_13)
    (open meiji_shrine day4 ts_14)
    (open meiji_shrine day4 ts_15)
    (open tsukiji_market day4 ts_6)
    (open tsukiji_market day4 ts_7)
    (open tsukiji_market day4 ts_8)
    (open tsukiji_market day4 ts_9)
    (open tsukiji_market day4 ts_10)
    (open tsukiji_market day4 ts_11)
    (open tsukiji_market day4 ts_12)
    (open tsukiji_market day4 ts_13)
    (open odaiba day4 ts_10)
    (open odaiba day4 ts_11)
    (open odaiba day4 ts_12)
    (open odaiba day4 ts_13)
    (open odaiba day4 ts_14)
    (open odaiba day4 ts_15)
    (open odaiba day4 ts_16)
    (open odaiba day4 ts_17)
    (open odaiba day4 ts_18)
    (open odaiba day4 ts_19)
    (open odaiba day4 ts_20)
    (open shinjuku_garden day4 ts_9)
    (open shinjuku_garden day4 ts_10)
    (open shinjuku_garden day4 ts_11)
    (open shinjuku_garden day4 ts_12)
    (open shinjuku_garden day4 ts_13)
    (open shinjuku_garden day4 ts_14)
    (open shinjuku_garden day4 ts_15)
    (open shinjuku_garden day4 ts_16)
    (open tokyo_tower day5 ts_10)
    (open tokyo_tower day5 ts_11)
    (open tokyo_tower day5 ts_12)
    (open tokyo_tower day5 ts_13)
    (open tokyo_tower day5 ts_14)
    (open tokyo_tower day5 ts_15)
    (open senso_ji day5 ts_8)
    (open senso_ji day5 ts_9)
    (open senso_ji day5 ts_10)
    (open senso_ji day5 ts_11)
    (open senso_ji day5 ts_12)
    (open senso_ji day5 ts_13)
    (open senso_ji day5 ts_14)
    (open senso_ji day5 ts_15)
    (open senso_ji day5 ts_16)
    (open senso_ji day5 ts_17)
    (open akihabara day5 ts_10)
    (open akihabara day5 ts_11)
    (open akihabara day5 ts_12)
    (open akihabara day5 ts_13)
    (open akihabara day5 ts_14)
    (open akihabara day5 ts_15)
    (open akihabara day5 ts_16)
    (open akihabara day5 ts_17)
    (open akihabara day5 ts_18)
    (open akihabara day5 ts_19)
    (open akihabara day5 ts_20)
    (open akihabara day5 ts_21)
    (open meiji_shrine day5 ts_8)
    (open meiji_shrine day5 ts_9)
    (open meiji_shrine day5 ts_10)
    (open meiji_shrine day5 ts_11)
    (open meiji_shrine day5 ts_12)
    (open meiji_shrine day5 ts_13)
    (open meiji_shrine day5 ts_14)
    (open meiji_shrine day5 ts_15)
    (open tsukiji_market day5 ts_6)
    (open tsukiji_market day5 ts_7)
    (open tsukiji_market day5 ts_8)
    (open tsukiji_market day5 ts_9)
    (open tsukiji_market day5 ts_10)
    (open tsukiji_market day5 ts_11)
    (open tsukiji_market day5 ts_12)
    (open tsukiji_market day5 ts_13)
    (open odaiba day5 ts_10)
    (open odaiba day5 ts_11)
    (open odaiba day5 ts_12)
    (open odaiba day5 ts_13)
    (open odaiba day5 ts_14)
    (open odaiba day5 ts_15)
    (open odaiba day5 ts_16)
    (open odaiba day5 ts_17)
    (open odaiba day5 ts_18)
    (open odaiba day5 ts_19)
    (open odaiba day5 ts_20)
    (open shinjuku_garden day5 ts_9)
    (open shinjuku_garden day5 ts_10)
    (open shinjuku_garden day5 ts_11)
    (open shinjuku_garden day5 ts_12)
    (open shinjuku_garden day5 ts_13)
    (open shinjuku_garden day5 ts_14)
    (open shinjuku_garden day5 ts_15)
    (open shinjuku_garden day5 ts_16)
  )

  (:goal (and
    (visited tokyo_tower)
    (visited senso_ji)
    (visited akihabara)
    (visited meiji_shrine)
    (visited tsukiji_market)
    (visited odaiba)
    (visited shinjuku_garden)
  ))
  (:metric minimize (total-cost))
)
